### PR TITLE
Added Lua 5.4 support to cmake build system

### PR DESCRIPTION
**Pull request by LinuxDonald**
Removed cmake files because cmake have them already.
Lua52 is something old that is not anymore needed FindLua searches for different Lua versions.
Set camek Version min to 3.18.1 because of Lua 5.4 support.

### CODE REVIEW

**Comment by nimetu** [comment]
I'm pretty sure you do not need to bump cmake min version all the way up to 3.22.

Ubuntu 20.04 (LTS) is at 3.16
Ubuntu 21.10 has cmake 3.18

I successfully compiled this using cmake 3.5 and lua5.3.

**Comment by LinuxDonald** [comment]
I will change it to version 3.18
hm Tag here say the oldest version what should have 5.4 support is 3.18
https://github.com/Kitware/CMake/commit/bbb7f0e27143f2780425c0b3b1004d749bfb7d4f#diff-f3e8905bf567bca98722602ea320c30077949ce5e9bfd6caf42c6d4733887bb4

**Comment by nimetu** [comment]
> I will change it to version 3.18 hm Tag here say the oldest version what should have 5.4 support is 3.18

It does not matter if dependency requires higher cmake version or not.

This cmake .txt file is usable with 3.5 at least. Probably even earlier versions, but I don't have any in handy.

cmake minimum version is project specific and should not copy minimum version from dependencies.

**Comment by LinuxDonald** [comment]
Should i set than 3.16.0 as version? That version is to available on Debian?

**Comment by nimetu** [comment]
I would leave it unchanged at 2.8 for now as there is no changes that require to change it.

**Comment by LinuxDonald** [comment]
Done

**Comment by kaetemi** [comment]
Yea. The generic FindLua seems fine and already handles all the 5.0 to 5.4 cases. It only exists since CMake 3.0.0, though!

**Pull request merged**
